/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Quiz.gui;

import Ouiz.Pojo.AnswerPojo;
import Ouiz.Pojo.AnswerStore;
import Ouiz.Pojo.ExamPojo;
import Ouiz.Pojo.PerformancePojo;
import Ouiz.Pojo.QuestionPojo;
import Ouiz.Pojo.QuestionStore;
import Ouiz.Pojo.UserProfile;
import Quiz.Dao.PerformanceDAO;
import Quiz.Dao.QuestionDAO;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author RC
 */
public class TakeTestFrame extends javax.swing.JFrame {
  private  QuestionStore qs;
 private AnswerStore astore;
   private int pos=0,qno;
    private String examId;
    Clocks c;
    ExamPojo exam=new ExamPojo();
    /**
     * Creates new form TakeTestFrame
     */
    public TakeTestFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
         c=new Clocks();
         c.start();
    }
    
    public TakeTestFrame(ExamPojo e){
        this();
        lblUserName2.setText("Hello "+UserProfile.getUserId());
        qs=new QuestionStore();
        astore=new AnswerStore();
        exam=e;
        lblTitle.setText(e.getLanguage().toUpperCase()+" Paper");
        qno=1;
        lblQno.setText(lblQno.getText()+" "+qno);
        loadQuestions();
        showQuestions();
    }
    
     public void loadQuestions(){
        examId=exam.getExamID();
        try{
            System.out.println("exam id"+ examId);
            ArrayList<QuestionPojo>list=QuestionDAO.getAllQuestionByID(examId);
            System.out.println("size of list"+list.size());
            //System.out.println("list item is"+list);
             //qs=new QuestionStore();
            for(QuestionPojo q:list){
            qs.addQuestion(q);
            }
             showQuestions();
            System.out.println(qs);
             int va=qs.getCount();
             System.out.println(va);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"problem in db","Error",JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }        
    }
     public void showQuestions(){
       buttonGroup1.clearSelection();
        QuestionPojo q=qs.getQuestion(pos);
        //System.out.println("questions in pojo"+q
        jrbOp1.setText(q.getAns1());
        jrbOp2.setText(q.getAns2());
        jrbOp3.setText(q.getAns3());
        jrbOp4.setText(q.getAns4());
        jtaQuestion.setText(q.getQuestion());
        AnswerPojo ans=astore.getAnswerByQno(qno);
        if(ans==null){
            return;
        }
        else{
            String str=ans.getChoosenAnswer();
           
            switch(str){
                case "Answer1":
                    jrbOp1.setSelected(true);
                    break;
                case "Answer2":
                    jrbOp2.setSelected(true);
                    break;
                case "Answer3":
                    jrbOp3.setSelected(true);
                    break;
                            
                case "Answer4":
                    jrbOp4.setSelected(true);
                    break;
            }
        }
        System.out.println("options one is"+q.getAns1());
        System.out.println("Option 2 is "+q.getAns2());
        System.out.println("Option 3 is "+q.getAns3());
        System.out.println("Option 4 is "+q.getAns4());
        System.out.println("langusage is "+q.getLanguage());
        System.out.println("exam id is "+q.getExamId());
        System.out.println("total question is "+qs.getCount());
        System.out.println("question is "+q.getQuestion());
        
        
    }
    private String getUserAnswer(){
     
        if(jrbOp1.isSelected())
            return "Answer1";
       else if(jrbOp2.isSelected())
            return "Answer2";
       else if(jrbOp3.isSelected())
            return "Answer3";
       else if(jrbOp4.isSelected())
            return "Answer4";
        else
           return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaQuestion = new javax.swing.JTextArea();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        lblQno = new javax.swing.JLabel();
        jrbOp1 = new javax.swing.JRadioButton();
        jrbOp2 = new javax.swing.JRadioButton();
        jrbOp3 = new javax.swing.JRadioButton();
        jrbOp4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        lblUserName2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 153, 102));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jtaQuestion.setColumns(20);
        jtaQuestion.setRows(5);
        jScrollPane1.setViewportView(jtaQuestion);

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 153, 102));
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 153, 102));
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 153, 102));
        jButton3.setText("cancel");

        btnDone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDone.setForeground(new java.awt.Color(255, 153, 102));
        btnDone.setText("done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        lblQno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQno.setForeground(new java.awt.Color(255, 153, 102));
        lblQno.setText("Question no");

        buttonGroup1.add(jrbOp1);
        jrbOp1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbOp1.setForeground(new java.awt.Color(255, 102, 51));
        jrbOp1.setText("jRadioButton4");

        buttonGroup1.add(jrbOp2);
        jrbOp2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbOp2.setForeground(new java.awt.Color(255, 102, 51));
        jrbOp2.setText("jRadioButton5");

        buttonGroup1.add(jrbOp3);
        jrbOp3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbOp3.setForeground(new java.awt.Color(255, 102, 51));
        jrbOp3.setText("jRadioButton6");

        buttonGroup1.add(jrbOp4);
        jrbOp4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrbOp4.setForeground(new java.awt.Color(255, 102, 51));
        jrbOp4.setText("jRadioButton7");

        jLabel1.setText("jLabel1");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 102, 51));
        lblTitle.setText("jLabel1");

        lblClock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 153, 102));
        lblClock.setText("jLabel2");

        lblUserName2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUserName2.setForeground(new java.awt.Color(255, 153, 0));
        lblUserName2.setText("jLabel2");

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\onlineexam\\good luck2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbOp1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrbOp2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrbOp3)
                        .addGap(96, 96, 96)
                        .addComponent(jrbOp4)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClock)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblQno)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(143, 143, 143))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(175, 175, 175))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)
                        .addGap(34, 34, 34))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnNext)
                        .addGap(51, 51, 51)
                        .addComponent(btnPrevious)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3)
                        .addGap(39, 39, 39)
                        .addComponent(btnDone))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(lblTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblUserName2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnLogout)))
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClock)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblQno)
                        .addGap(76, 76, 76)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbOp1)
                    .addComponent(jrbOp2))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbOp3)
                    .addComponent(jrbOp4))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious)
                    .addComponent(jButton3)
                    .addComponent(btnDone))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Login l=new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
      
        String choosenAns=getUserAnswer();
        if(choosenAns!=null){
            System.out.println("hello");
         QuestionPojo quest=qs.getQuestionByQno(qno);
         String correctAns=quest.getCorrect_ans();
         AnswerPojo ans=new AnswerPojo();
         ans.setChoosenAnswer(choosenAns);
         ans.setCorrectAnswer(correctAns);
         ans.setQno(qno);
         ans.setExamid(exam.getExamID());
         ans.setSubject(exam.getLanguage());
         AnswerPojo attemped=astore.getAnswerByQno(qno);
         if(attemped==null){
             astore.addAnswer(ans);
         }
         else{
             System.out.println("hiii");
             String previousAns=attemped.getChoosenAnswer();
             if(choosenAns.equalsIgnoreCase(previousAns)==false){
                int apos=astore.removeAnswer(ans);
                astore.setAnswer(apos, ans);
             }
         }
        }
         pos++;
           if(pos>=qs.getCount()){
            pos=0;
           }
           
           qno++;
             if(qno>qs.getCount()){
                 qno=1;
           }
        lblQno.setText("Question no :"+qno);
        showQuestions();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
      
         String choosenAns=getUserAnswer();
        if(choosenAns!=null){
         QuestionPojo quest=qs.getQuestionByQno(qno);
         String correctAns=quest.getCorrect_ans();
         AnswerPojo ans=new AnswerPojo();
         ans.setChoosenAnswer(choosenAns);
         ans.setCorrectAnswer(correctAns);
         ans.setQno(qno);
         ans.setExamid(exam.getExamID());
         ans.setSubject(exam.getLanguage());
         AnswerPojo attemped=astore.getAnswerByQno(qno);
         if(attemped==null){
             astore.addAnswer(ans);
         }
         else{
             String previousAns=attemped.getChoosenAnswer();
             if(choosenAns.equalsIgnoreCase(previousAns)==false){
                int apos=astore.removeAnswer(ans);
                astore.setAnswer(apos, ans);
             }
         }
        }
         pos--;
           if(pos<0){
            pos=qs.getCount()-1;
           }
           
           qno--;
             if(qno<=0){
                 qno=qs.getCount();
           }
        lblQno.setText("Question no :"+qno);
        showQuestions();
    }//GEN-LAST:event_btnPreviousActionPerformed
       public void doneTest(){
            String choosenAns=getUserAnswer();
        if(choosenAns!=null){
         QuestionPojo quest=qs.getQuestionByQno(qno);
         String correctAns=quest.getCorrect_ans();
         AnswerPojo ans=new AnswerPojo();
         ans.setChoosenAnswer(choosenAns);
            System.out.println(choosenAns);
         ans.setCorrectAnswer(correctAns);
         ans.setQno(qno);
         ans.setExamid(exam.getExamID());
         ans.setSubject(exam.getLanguage());
         AnswerPojo attemped=astore.getAnswerByQno(qno);
         if(attemped==null){
             astore.addAnswer(ans);
         }
          else{
             String previousAns=attemped.getChoosenAnswer();
             if(choosenAns.equalsIgnoreCase(previousAns)==false){
                int apos=astore.removeAnswer(ans);
                astore.setAnswer(apos, ans);
             }
        }
        }
        int right=0,wrong=0,unattempted=0;
        for(QuestionPojo q:qs.getAllQuestion()){
            int qno=q.getQno();
            AnswerPojo ans=astore.getAnswerByQno(qno);
            System.out.println("ans is "+ans);
            if(ans==null){
                ++unattempted;
            }
            else{
            String attemptedAns=ans.getChoosenAnswer();
            String correctAns=ans.getCorrectAnswer();
            if(attemptedAns.equals(correctAns)){
                ++right;
            }
            else{
                ++wrong;
            }
            }
        }
        StringBuilder sb=new StringBuilder();
        sb.append("right ans: "+right);
        sb.append("wrong ans: "+wrong);
        sb.append("unattempted ans: "+unattempted);
        JOptionPane.showMessageDialog(null,sb.toString(),"result",JOptionPane.INFORMATION_MESSAGE);
        try{
            PerformancePojo performance=new PerformancePojo();
            performance.setExamid(exam.getExamID());
            performance.setLanguage(exam.getLanguage());
            performance.setUserid(UserProfile.getUserId());
            performance.setRight(right);
            performance.setUnattemp(unattempted);
            performance.setWrong(wrong);
            performance.setPer((double)right/qs.getCount()*100);
            PerformanceDAO.addPerformance(performance);
          JOptionPane.showMessageDialog(null,"result Saved thanku for the test","done",JOptionPane.INFORMATION_MESSAGE);
          PaperSelectionFrame f=new PaperSelectionFrame();
          f.setVisible(true);
          this.dispose();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"problem in TakeTest","Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            System.out.println(ex);

        }
       }
    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        doneTest();
    }//GEN-LAST:event_btnDoneActionPerformed
    class Clocks extends Thread{
        int time=0;
          int m=1,s=60,h=0;
       public void run(){
       while(true){
               Calendar date=Calendar.getInstance();
               date.setTime(new Date());
               date.set(Calendar.HOUR_OF_DAY, h);
               date.set(Calendar.MINUTE, m);
               date.set(Calendar.SECOND, s);
               date.set(Calendar.MILLISECOND, 0);
               Date da=date.getTime();
               SimpleDateFormat sdf=new SimpleDateFormat("HH:mm:ss");
               String str=sdf.format(da);
               
        try{
            Thread.sleep(1000);
            s=s-1;
            if(s==0){
                m=m-1;
                s=60;
                time=time+1;
            }
            
            //time=time+1000;
            lblClock.setText(str);
            }
            catch(InterruptedException ex){
                System.out.println(ex);
            }
           if(time==2){
               lblClock.setText("00:00:00");
               JOptionPane.showMessageDialog(null, " time is finished press done to submit exam","time completed",JOptionPane.INFORMATION_MESSAGE);
               //doneTest();
               btnNext.setEnabled(false);
               btnPrevious.setEnabled(false);
               break;
           }
       }
         }
    }
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbOp1;
    private javax.swing.JRadioButton jrbOp2;
    private javax.swing.JRadioButton jrbOp3;
    private javax.swing.JRadioButton jrbOp4;
    private javax.swing.JTextArea jtaQuestion;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblQno;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName2;
    // End of variables declaration//GEN-END:variables
}
